name: robograsp310
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - aom=3.5.0=h27087fc_0
  - attr=2.5.2=h39aace5_0
  - brotlicffi=1.0.9.2=py310hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.16.0=ha61ee94_1012
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_1
  - charset-normalizer=3.4.4=py310h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h3c4dab8_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_hf1063bd_110
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - gettext=0.25.1=h5888daf_0
  - gettext-tools=0.25.1=h5888daf_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.41=h17648ed_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_hb72d44e_103
  - icu=70.1=h27087fc_0
  - idna=3.11=py310h06a4308_0
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jpeg=9e=h166bdaf_1
  - json-numpy=2.1.1=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h8e693c7_0
  - libasprintf-devel=0.25.1=h8e693c7_0
  - libavif=0.11.1=h8182462_2
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.1.2=h409715c_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt=1.11.1=ha770c72_0
  - libgcrypt-devel=1.11.1=hb9d3cd8_0
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgcrypt-tools=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h5888daf_0
  - libgettextpo-devel=0.25.1=h5888daf_0
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.4=h77a78f3_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.8=hfac485b_1
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblapacke=3.9.0=38_h6ae95b6_openblas
  - libllvm15=15.0.7=hadd5161_1
  - libltdl=2.4.3a=h5888daf_0
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=h46f56fc_0
  - libopencv=4.7.0=py310hb48cf42_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=15.3=hbcd7760_1
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=253=h8c4010b_1
  - libtasn1=4.20.0=hb03c661_1
  - libtiff=4.5.1=hffd6297_1
  - libtool=2.5.4=h5888daf_0
  - libudev1=253=h0b41bf4_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mpg123=1.32.9=hc50e24c_0
  - mysql-common=8.0.33=hf1915f5_2
  - mysql-libs=8.0.33=hca2cd23_2
  - ncurses=6.5=h7934f7d_0
  - nettle=3.9.1=h7ab15ed_0
  - nspr=4.37=h29cc59b_0
  - nss=3.117=h445c969_0
  - opencv=4.7.0=py310hff52083_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.8=h7b32b05_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.46=hf426167_0
  - pillow=9.4.0=py310h023d228_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - py-opencv=4.7.0=py310hfdc917e_1
  - pycparser=2.23=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - qt-main=5.15.6=h602db52_6
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - svt-av1=1.4.1=hcb278e6_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - mecheyeapi==2.5.2
      - numpy==2.2.6
      - pyaubo-sdk==0.24.1
prefix: /home/rory/miniconda3/envs/robograsp310
